### ISSUE TITLE
Accept function

### ISSUE THREAD

**Issue by fregante** [sindresorhus/p-timeout#31]
I think this is the natural evolution of this module:

```js
async function pingApi() {
	await fetch('/api');
}

await pTimeout(pingApi, {
	milliseconds: 50,
});
```

Or even wrapping it a-la-p-memoize:

```js
const timedPingApi = pTimeout.function(async() {
	await fetch('/api');
}, {
	milliseconds: 50,
});

await timedPingApi()
```

In both cases, `pTimeout` can also generate a signal:

```diff
+ async function pingApi(signal) {
+ 	await fetch('/api', {signal});
}

await pTimeout(pingApi, {
	milliseconds: 50,
});
```

which is otherwise super verbose currently:

```js
const controller = new AbortController()
async function pingApi(signal) {
	await fetch('/api', {signal});
}

const promise = pingApi(signal);

try {
	await pTimeout(promise, {
		milliseconds: 50,
	});
} finally {
	controller.abort()
}
```

Or it can also pass it around, if it already exists:

```diff
async function pingApi(signal) {
	await fetch('/api', {signal});
}

await pTimeout(pingApi, {
+	signal,
	milliseconds: 50,
});
```

**Comment by sindresorhus** [comment]
Makes sense.

So `pTimeout` accepts a function too, which receives a `signal`.

And also a separate named export called `wrapWithTimeout` (please find a better name 🙏) to wrap functions. It would receive the signal as the first argument and then the past arguments next (so the passed in arguments are shifted by one).

**Comment by fregante** [comment]
So this should have two parts, right? 

- `pTimeout` should also accept a function that will be called immediately
- `createFunctionWithTimeout` accepts and returns a function

**Comment by sindresorhus** [comment]
Correct

**Comment by fregante** [comment]
> * `pTimeout` should also accept a function that will be called immediately

Now that `AbortSignal` is more common, I think `p-timeout` should only be used if the function doesn't accept a signal. This is because without a `signal`, the internal function will continue uninterrupted, which is bad.

The solution to my "verbose" example is:

```js
async function pingApi(signal) {
	await fetch('/api', {signal});
}

await pingApi(AbortSignal.timeout(50));
```

Or if there's a pre-existing `signal`, use AbortSignal.any() or https://github.com/fregante/abort-utils/blob/main/source/merge-signals.md

```js
await pingApi(AbortSignal.any([otherSignal, AbortSignal.timeout(50)]);
```


> * `createFunctionWithTimeout` accepts and returns a function

Given the `pingApi` above, if we want to have it timeout, instead of 

```js
const pingWithTimeout = createFunctionWithTimeout(pingApi, 500)
await pingWithTimeout();
```

You can

```js
const pingWithTimeout = () => pingApi(AbortSignal.timeout(500));
await pingWithTimeout();
```

or just specify it as needed

```js
await pingApi(AbortSignal.timeout(500))
```

---

The major difference between `AbortSignal` and `p-timeout` is that `AbortSignal` lets the function decide how to deal with a time out, for better or for worse, because the function can resolve with `undefined` instead of throwing an error.

However there's a solution to that too:

```js
const timeout = AbortSignal.timeout(500);
await pingApi(timeout);
timeout.throwIfAborted(); // This line will be reached if pingApi doesn't already throw
```

**Comment by sindresorhus** [comment]
Yeah. I still strongly dislike the AbortController API though, but it's the best we got...

**Comment by sindresorhus** [comment]
Maybe worth documenting the AbortController timeout alternative in the readme.

**Comment by fregante** [comment]
Can do. Where? As an alternative at the bottom? As a deprecation message? As a note/link at the top that points to a section at the bottom?

**Comment by sindresorhus** [comment]
Note at top with link to bottom.

**Comment by fregante** [comment]
I'm gonna use this issue to document how to replicate p-timeout's options:

## message

If the function throws an error on `abort` (like `fetch`) and you want to customize it, you have to catch it and rethrow:

```js
try {
  await fetch('/api', {signal: AbortSignal.timeout(50)});
} catch (error) {
  if (error.name === 'TimeoutError') { // Chrome actually doesn't use this name 🥲
    throw new Error('Too slow')
  }
}
```

If it doesn't throw:

```js
const timeout = AbortSignal.timeout(50);
await myAsyncFunction({signal: timeout});
if (timeout.aborted) {
    throw new Error('Too slow')
}
```

## fallback

Like before, but just run your fallback code instead of `throw`ing

## customTimers

Since it's a native feature, refer to your test runner docs, or use https://github.com/whatwg/dom/issues/951#issuecomment-922833719

**Comment by fregante** [comment]
Admittedly, customizing the error is more verbose than with p-timeout (however it lacks the `signal` on `fetch`, so we're back to square one):

```js
await pTimeout(fetch('/api'), {
  milliseconds: 50,
  message: 'Too slow',
});
```
