### ISSUE TITLE
Make the resulting promise cancelable

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/p-timeout#6]
See: https://github.com/sindresorhus/p-timeout/pull/3#issuecomment-338468130

**Comment by agirorn** [comment]
I guess this issues should be closed.

**Comment by sindresorhus** [comment]
@agirorn No, it's not done. See my comment: https://github.com/sindresorhus/p-timeout/pull/3#issuecomment-338468130

**Comment by szmarczak** [comment]
Maybe use `p-cancelable`?

**Comment by szmarczak** [comment]
```js
new PTimeout(resolve, reject, onCancel, onTimeout) {
...
}
```
