### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by ZeeCoder** [sindresorhus/p-timeout#9]
This is more of a question than an actual issue, and not only related to this library.

At first I started using these packages as is using webpack, like: p-defer, delay, p-timeout etc.

I assumed that all of these are isomorphic packages, which they sort of are in the sense that they work both in Node and the browser.

It seems I was mistaken however, since the latter needs an extra transpilation step.
(For not-so-modern browsers without const/let etc support anyway.)

This was not an obvious tradeoff to me as I started mass-consuming these packages all over, and I only found out that there's an issue, once I looked at a critical application using Browserstack.

My setup basically wasn't transpiling anything coming from `node_module`, which is a very usual setup.
At first I tried to just transpile the whole thing, but that not only increased the build time 4 times, it also introduced other bugs I just couldn't figure out.

For the time being I've whitelisted these packages, and it seems to work.
However that's obviously a very tedious and manual process, and there's no guarantee I wouldn't encounter an other one of your packages (targeted at Node4 for example, instead of the browser) as a transitive dependency without realising it.

I'm curious what you think of the situation.
I can't say it's wrong how these packages are published, since they work just as they meant to work in their target environment: Node.

However I do wonder if there's an easier solution to use your libraries in the browser, without the setup I described above, since this issue basically now stops me from using more of your packages. 😢

Even if, say, you decided to actually use an extra build step to transpile your libraries for the browser-env, I see no obvious way of serving both es5 and es6 code at the same time, separately to the browser and Node.

As a lib author who might want to publish such an isomorphic package in the future, it's a real concern for me how tooling currently doesn't seem to help the situation. 🤔

**Comment by SamVerschueren** [comment]
You can read more about it here https://github.com/sindresorhus/ama/issues/446.

You can also check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by ZeeCoder** [comment]
That's what I thought, thank you for the quick response @SamVerschueren !
That plugin might just be what I need too, seems like a generic solution that'd cover all such modules, and not only the ones I whitelisted.
I'll definitely give it a go. 👍
